language: node_js
node_js:
  - "0.10"
  - "4.4.3"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-utils
  - npm install -g npm@2.13.5
  - npm install -g grunt-cli
install: npm install
